import { colors, fonts, radii, spacing, strokes } from "../../styles/theme";
import { cardSurface } from "../Card/Card.styles";

export const styles = {
  card: {
    // Sage clinic surface — shared with ClinicCard via cardSurface
    // (the lone literal shadow is now the shadows.card token).
    ...cardSurface("sage", "raised"),
    padding: spacing["2xl"],
    width: "373px",
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing.xl,
    position: "relative" as const,
  },
  header: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    gap: spacing.xs,
  },
  clinicTitle: {
    fontFamily: fonts.family.secondary,
    fontSize: fonts.size.h4,
    fontWeight: fonts.weight.regular,
    color: colors.neutral900,
    margin: 0,
    textAlign: "left" as const,
  },
  domainSection: {
    display: "flex",
    width: "100%",
    height: "40px",
    borderRadius: radii.m,
    overflow: "hidden",
    border: `${strokes.xs} solid ${colors.neutral300}`,
  },
  domainPrefix: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    padding: `0 ${spacing.xs}`,
    backgroundColor: colors.neutralAlphaBlack,
    fontSize: fonts.size.m,
    color: colors.neutral500,
  },
  domainSuffix: {
    width: "125px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.neutralAlphaBlack,
    borderLeft: `${strokes.xs} solid ${colors.neutral300}`,
    fontSize: fonts.size.m,
    color: colors.neutral500,
  },
  infoList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing.s,
  },
  infoItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: spacing.xs,
    padding: spacing.xs,
    backgroundColor: colors.neutralAlphaBlack,
    borderRadius: "4px",
  },
  iconWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    flexShrink: 0,
  },
  infoText: {
    fontSize: fonts.size.m,
    color: colors.neutral500,
    margin: 0,
    lineHeight: "22px",
  },
  addressText: {
    fontSize: fonts.size.s,
    color: colors.neutral500,
    margin: 0,
    lineHeight: "20px",
  },
  tagList: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "4px",
  },
  tag: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary300,
    color: colors.neutral100,
    padding: "4px 12px",
    borderRadius: radii.pill,
    fontSize: fonts.size.xs,
    whiteSpace: "nowrap" as const,
  },
  tagRemove: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    padding: 0,
    display: "flex",
    alignItems: "center",
  },
  footer: {
    marginTop: "auto",
    display: "flex",
    justifyContent: "center",
  }
} as const;
