import { colors, fonts, radii, spacing, strokes, rem } from "../../styles/theme";

export const styles = {
  card: {
    backgroundColor: colors.secondary50,
    borderRadius: radii.xxl,
    padding: spacing.xxl,
    width: rem(373),
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing.xl,
    position: "relative" as const,
    boxShadow: "0 4px 20px rgba(0,0,0,0.04)",
  },
  header: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    gap: spacing.xs,
  },
  clinicTitle: {
    fontFamily: fonts.family.secondary,
    fontSize: fonts.size.h4,
    fontWeight: fonts.weight.regular,
    color: colors.neutral900,
    margin: 0,
    textAlign: "left" as const,
  },
  domainSection: {
    display: "flex",
    width: "100%",
    height: rem(40),
    borderRadius: radii.m,
    overflow: "hidden",
    border: `${strokes.xs} solid ${colors.neutral300}`,
  },
  domainPrefix: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    padding: `0 ${spacing.xs}`,
    backgroundColor: colors.neutralAlphaBlack,
    fontSize: fonts.size.m,
    color: colors.neutral500,
  },
  domainSuffix: {
    width: rem(125),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.neutralAlphaBlack,
    borderLeft: `${strokes.xs} solid ${colors.neutral300}`,
    fontSize: fonts.size.m,
    color: colors.neutral500,
  },
  infoList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing.s,
  },
  infoItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: spacing.xs,
    padding: spacing.xs,
    backgroundColor: colors.neutralAlphaBlack,
    borderRadius: rem(4),
  },
  iconWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: rem(24),
    height: rem(24),
    flexShrink: 0,
  },
  infoText: {
    fontSize: fonts.size.m,
    color: colors.neutral500,
    margin: 0,
    lineHeight: rem(22),
  },
  addressText: {
    fontSize: fonts.size.s,
    color: colors.neutral500,
    margin: 0,
    lineHeight: rem(20),
  },
  tagList: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: rem(4),
  },
  tag: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary300,
    color: colors.neutral100,
    padding: `${rem(4)} ${rem(12)}`,
    borderRadius: radii.pill,
    fontSize: fonts.size.xs,
    whiteSpace: "nowrap" as const,
  },
  tagRemove: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    padding: 0,
    display: "flex",
    alignItems: "center",
  },
  footer: {
    marginTop: "auto",
    display: "flex",
    justifyContent: "center",
  }
} as const;
