version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: docodile-postgres
    restart: always
    environment:
      POSTGRES_DB: docodile
      POSTGRES_USER: docodile
      POSTGRES_PASSWORD: docodile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
