import { CSSProperties } from "react";
import { colors, fonts, radii, spacing, strokes } from "../../styles/theme";

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1300,
    padding: spacing.l,
    paddingBottom: 96,
  },
  shell: {
    display: "flex",
    flexDirection: "row",
    width: "min(1100px, 94vw)",
    height: "min(680px, calc(100vh - 160px))",
    backgroundColor: colors.neutral100,
    borderRadius: radii.xl,
    overflow: "hidden",
    boxShadow: "0 16px 48px rgba(0, 0, 0, 0.18)",
  },

  previewPane: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.neutral700,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: spacing.l,
    overflow: "auto",
  },
  previewPage: {
    width: "100%",
    maxWidth: 520,
    aspectRatio: "1 / 1.414",
    backgroundColor: colors.neutral100,
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.12)",
    border: "none",
    flexShrink: 0,
  },

  settingsPane: {
    width: 340,
    flexShrink: 0,
    backgroundColor: colors.neutral100,
    display: "flex",
    flexDirection: "column",
    padding: spacing.xl,
    borderLeft: `${strokes.xs} solid ${colors.primary300}`,
  },
  settingsHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    paddingBottom: spacing.l,
    borderBottom: `${strokes.xs} solid ${colors.primary300}`,
  },
  settingsTitle: {
    margin: 0,
    fontFamily: fonts.family.primary,
    fontSize: fonts.size.h6,
    lineHeight: fonts.lineHeight.h6,
    fontWeight: fonts.weight.regular,
    color: colors.neutral900,
  },
  pageCount: {
    fontFamily: fonts.family.primary,
    fontSize: fonts.control.sm,
    color: colors.neutral500,
  },

  fieldList: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.m,
    paddingTop: spacing.l,
    flex: 1,
    overflow: "auto",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.xs,
  },
  fieldLabel: {
    fontFamily: fonts.family.primary,
    fontSize: fonts.control.xs,
    color: colors.neutral500,
  },
  select: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 40,
    padding: `0 ${spacing.s}`,
    backgroundColor: colors.primary100,
    border: "none",
    borderRadius: radii.m,
    fontFamily: fonts.family.primary,
    fontSize: fonts.control.sm,
    color: colors.neutral900,
    cursor: "default",
  },
  selectIconWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: colors.neutral700,
  },

  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: spacing.xs,
    paddingTop: spacing.l,
    borderTop: `${strokes.xs} solid ${colors.primary300}`,
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: spacing.s,
  },
  configureBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "transparent",
    border: "none",
    padding: spacing["3xs"],
    cursor: "pointer",
    color: colors.neutral700,
    borderRadius: radii.xs,
  },
  shareBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: colors.neutral900,
  },

  menu: {
    position: "absolute" as const,
    top: "calc(100% + 4px)",
    left: 0,
    right: 0,
    backgroundColor: colors.neutral100,
    border: `${strokes.xs} solid ${colors.primary300}`,
    borderRadius: radii.m,
    padding: spacing["2xs"],
    boxShadow: "0 4px 16px rgba(0,0,0,0.08)",
    zIndex: 1310,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  menuItem: {
    width: "100%",
    textAlign: "left" as const,
    padding: `${spacing.xs} ${spacing.s}`,
    fontFamily: fonts.family.primary,
    fontSize: fonts.control.sm,
    color: colors.neutral900,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    borderRadius: radii.xs,
  },
  menuItemActive: {
    backgroundColor: colors.primary100,
    color: colors.neutral900,
  },
};
