import { CSSProperties } from "react";
import { colors, fonts, spacing, radii } from "../../styles/theme";

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: colors.neutral100,
    borderRadius: radii.primary,
    padding: spacing.xl,
    width: "100%",
    maxWidth: 480,
    maxHeight: "90vh",
    overflowY: "auto",
    fontFamily: fonts.family.primary,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.xl,
  },
  title: {
    fontSize: fonts.size.h5,
    fontWeight: fonts.weight.semibold,
    color: colors.blindBlack,
    margin: 0,
  },
  closeButton: {
    background: "none",
    border: "none",
    fontSize: fonts.size.h5,
    cursor: "pointer",
    color: colors.neutral600,
    padding: 0,
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    fontSize: fonts.size.s,
    fontWeight: fonts.weight.medium,
    color: colors.neutral600,
    marginBottom: spacing.s,
    textTransform: "uppercase" as const,
    letterSpacing: "0.5px",
  },
  searchContainer: {
    position: "relative",
  },
  searchInput: {
    width: "100%",
    padding: spacing.m,
    borderRadius: radii.m,
    border: `1px solid ${colors.neutral300}`,
    fontSize: fonts.size.m,
    fontFamily: fonts.family.primary,
    boxSizing: "border-box",
  },
  searchResults: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: colors.neutral100,
    border: `1px solid ${colors.neutral300}`,
    borderRadius: radii.m,
    marginTop: 4,
    maxHeight: 200,
    overflowY: "auto",
    zIndex: 10,
  },
  searchResultItem: {
    padding: spacing.m,
    cursor: "pointer",
    borderBottom: `1px solid ${colors.neutral200}`,
  },
  searchResultName: {
    fontSize: fonts.size.m,
    fontWeight: fonts.weight.medium,
    color: colors.blindBlack,
    margin: 0,
  },
  searchResultMeta: {
    fontSize: fonts.size.s,
    color: colors.neutral600,
    margin: 0,
  },
  selectedPatient: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing.m,
    backgroundColor: colors.secondary50,
    borderRadius: radii.m,
    border: `1px solid ${colors.secondary300}`,
  },
  selectedPatientInfo: {
    flex: 1,
  },
  changeButton: {
    background: "none",
    border: "none",
    color: colors.secondary600,
    fontSize: fonts.size.s,
    cursor: "pointer",
    textDecoration: "underline",
  },
  formRow: {
    display: "flex",
    gap: spacing.m,
    marginBottom: spacing.m,
  },
  formGroup: {
    flex: 1,
  },
  label: {
    display: "block",
    fontSize: fonts.size.s,
    fontWeight: fonts.weight.medium,
    color: colors.neutral700,
    marginBottom: spacing.xs,
  },
  input: {
    width: "100%",
    padding: spacing.s,
    borderRadius: radii.m,
    border: `1px solid ${colors.neutral300}`,
    fontSize: fonts.size.m,
    fontFamily: fonts.family.primary,
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: spacing.s,
    borderRadius: radii.m,
    border: `1px solid ${colors.neutral300}`,
    fontSize: fonts.size.m,
    fontFamily: fonts.family.primary,
    backgroundColor: colors.neutral100,
    boxSizing: "border-box",
  },
  typeToggle: {
    display: "flex",
    gap: spacing.s,
  },
  typeButton: {
    flex: 1,
    padding: spacing.m,
    borderRadius: radii.m,
    border: `1px solid ${colors.neutral300}`,
    backgroundColor: colors.neutral100,
    fontSize: fonts.size.m,
    fontWeight: fonts.weight.medium,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  typeButtonActive: {
    backgroundColor: colors.secondary100,
    borderColor: colors.secondary500,
    color: colors.secondary700,
  },
  divider: {
    display: "flex",
    alignItems: "center",
    margin: `${spacing.m} 0`,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.neutral300,
  },
  dividerText: {
    padding: `0 ${spacing.m}`,
    color: colors.neutral500,
    fontSize: fonts.size.s,
  },
  footer: {
    display: "flex",
    gap: spacing.m,
    marginTop: spacing.xl,
  },
  errorText: {
    color: colors.red200,
    fontSize: fonts.size.s,
    marginTop: spacing.xs,
  },
};
