-- Seed dermatology diagnosis suggestions. Field = 'diagnosis', specialty
-- = 'dermatology' (matches the lowercase + trimmed normalization done by
-- SuggestionService.resolveSpecialities). Idempotent via ON CONFLICT so
-- this migration is safe to re-run if it's ever replayed.

-- gen_random_uuid() is core in Postgres 13+; pgcrypto provides it on older
-- versions. Safe no-op on newer ones.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO suggestion (id, speciality, field, value, use_count, created_at) VALUES
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ACNE VULGARIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TELOGEN EFFLUVIUM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PITYRIASIS CAPITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ALLERGIC CONTACT DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TINEA CORPORIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'MELASMA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SCABIES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ACANTHOSIS NIGRICANS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TINEA CRURIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PMLE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PRURIGO SIMPLEX', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'AGA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'POST INFLAMMATORY HYPERPIGMENTATION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TINEA INCOGNITO', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'DPNS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ACNEIFORM ERUPTION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ACUTE URTICARIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'GRADE 2', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PERIORBITAL MELANOSES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TRUNCAL ACNE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SEBORRHEIC DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ALOPECIA AREATA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'DPN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'RIEHLS MELANOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TSDF', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'HERPES ZOSTER', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PITYRIASIS ALBA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'KERATOSIS PILARIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'FACIAL MELANOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PITYRIASIS FOLLICULITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CHRONIC URTICARIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SEBORRHEIC CAPITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PITYRIASIS VERSICOLOR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'FISSURE FEET', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'HIRSUTISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PERIORAL MELANOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CHRONIC PLAQUE PSORIASIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'STASIS DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'FEMALE PATTERN HAIRLOSS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PIH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PEDICULOSIS CAPITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'MACULAR AMYLOIDOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'GRADE 3', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ATROPHIC ACNE SCARS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ANDROGENETIC ALOPECIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'XEROSIS CUTIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PITYRIASIS ROSEA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TO HAIR DYE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'EYELID ECZEMA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'INTERTRIGO', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'HAND ECZEMA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'STASIS ECZEMA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'TO DETERGENT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'IRRITANT CONTACT DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PREMATURE CANITIES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CORN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'LICHEN PLANUS PIGMENTOSUS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'FRICTIONAL MELANOSES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'NUMMULAR ECZEMA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CALLOSITY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'MILIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ONYCHOMYCOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SCALP FOLLICULITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SENILE XEROSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'LICHEN PLANUS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'FOLLICULITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PAPULAR URTICARIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ACD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ATOPIC DIATHESIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SEBOPSORIASIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'EARLY AGA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SEBACEOUS CYST', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ACNE EXCORIEE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'BINDI DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ATOPIC DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', '? SWEAT DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'VERRUCA VULGARIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PALMOPLANTAR PSORIASIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'POST ACNE ATROPHIC SCARS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SCROTAL DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CANDIDAL BALANOPOSTHITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PRURIGO NODULARIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PLANTAR WART', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SCALP PSORIASIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'PALMAR PSORIASIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ATROPHIC SCARS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'RETINOID DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'DANDRUFF', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'LIP LICKERS DERMATITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CHRONIC LICHENIFIED ECZEMA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'ABSCESS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'INSECT BITE REACTION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'VARICELLA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'SECONDARY BACTERIAL INFECTION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'KELOID', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'GRADE1', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'DERMOGRAPHISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'POMPHOLYX', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'CHRONIC SPONTANEOUS URTICARIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'diagnosis', 'LSC', 0, now())
ON CONFLICT (speciality, field, value) DO NOTHING;
