-- Seed dermatology complaint suggestions. Field = 'complaints', specialty
-- = 'dermatology' (matches the lowercase + trimmed normalization done by
-- SuggestionService.resolveSpecialities). Idempotent via ON CONFLICT so
-- this migration is safe to re-run if it's ever replayed.
INSERT INTO suggestion (id, speciality, field, value, use_count, created_at) VALUES
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HAIRFALL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER TRUNK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHING ALL OVER BODY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH OVER THE GROIN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'BLACK SPOTS OVERFACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HAIR THINNING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY LESIONS OVER LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DANDRUFF', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DARK SPOTS OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PUS DISCHARGE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'CAME FOR SKIN CARE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PIMPLES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'WHITE SPOTS OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER HANDS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SCALING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'BLACK SPOTS OVER THE FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ACNE VULGARIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH ALL OVER THE BODY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER ARMS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHING OVER SCALP', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'REDNESS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SCALING AND ITCHING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'BLACK SPOTS OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHING LEG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HAIR FALL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'EXCESSIVE SWEATING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'CASE REVIEWED. IMPROVEMENT NOTED.', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'NO H/O FEVER', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SWELLING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'OVER THE NECK SINCE 18 YEARS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PIGMENTATION OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'REDNESS OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESI0ON OVER GENITALIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER CHEST REGION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHING OVER THE SCROTUM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'FISSURES OVER THE LIPS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY OOZY LESIONS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PIMPLES OVER FACE AND TRUNK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PIGMENTATION OVER THE CHEEKS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER TRUNK AND ARMS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HAIRLOSS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SMALL HYPERPIGMENTED LESIONS OVER NECK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RED RAISED LESIONS OVER KNEES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PIGMENTATION AROUND NOSE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DARK CIRCLES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'H/O USAGE OF SKINSHINE CREAM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'H/O USAGE OF SKINSHINE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DRYNESS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SCALY LESIONS OVER THE BODY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SINUS OVER THE LEFT CHEEK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER THE NOSE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHING AND SCALING OVER THE SCALP AND BEARD AREA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER LATERAL ASPECT OF ARMS,LEGS AND BUTTOCKS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'RAISED LESIONS OVER RT BREAST AND CHEST', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'KCO BREAST CA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RAISED LESIONS OVER THE SCROTUM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'VIOLACEOUS HUE PRESENT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PAINFUL RED RAISED LESION OVER RT AXILLA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SKIN TAG OVER GROIN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'KCO PCOD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PAINFUL FISSURES OVER THE LIPS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY SCALY LESIONS OVER THE FLEXURES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'FISSURING OVER THE FEET', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SKIN TAGS OVER NECK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH OVER THE ARMS AND LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SKIN PEELING OVER THE FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCY RASH ALL OVER THE BODY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'SIMILAR COMPLAINTS IN THE FAMILY IN TWO OTHER KIDS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HISTORY OF ATOPY PRESENT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DRY SKIN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'EXCESSIVE HAIR GROWTH OVER CHIN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DARK PATCHES OVER LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HAIR LOSS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH OVER THE PALMS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH OVER THE LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PATCHY HAIR LOSS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'NECK DARKNESS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'PAINFUL LESIONS OVER FEET', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ITCHY RASH OVER BUTTOCKS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DARKENING OF SKIN OVER FACE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'OVER PALMS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'ELBOWS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'OVER ARMS AND LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'DRYNESS OF SKIN ALL OVER THE BODY SINCE 2 YEARS OF AGE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'C/O FLUID FILLED LESIONS OVER LEGSC/O ASYMPTOMATIC WHITE PATCHES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'C/O DECREASED SENSATIONS OVER BOTH LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'C/O TINGLING SENSATION OVER BOTH HANDS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'NO H/O BLEEDING FROM NOSE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'H/O SLIPPAGE OF FOOTWEAR+', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'NO H/O HOARSENESS OF VOICE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'FAMILY H/O +. HANSENS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'FAMILY H/O + HANSENS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'O/E-', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'C/O FLUID FILLED LESIONS OVER LEGS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'C/O ASYMPTOMATIC WHITE PATCHES OVER TRUNK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'O/E-ILL DEFINED', 0, now()),
  (gen_random_uuid(), 'dermatology', 'complaints', 'HYPOPIGMENTED PATCHES & MACULES NOTED OVER TRUNK & B/L LL & UL', 0, now())
ON CONFLICT (speciality, field, value) DO NOTHING;
