-- Seed dermatology personal-history suggestions. Field = 'personal_history',
-- specialty = 'dermatology' (matches the lowercase + trimmed normalization
-- done by SuggestionService.resolveSpecialities). Idempotent via ON CONFLICT.
INSERT INTO suggestion (id, speciality, field, value, use_count, created_at) VALUES
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Smoking', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Smoking (1-5 in a day)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Smoking (5-10 in a day)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Smoking (More than 10 in a day)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Smoking (Occasionally)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Smoking (Quit)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Drinking (Occasionally)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Drinking (Moderate)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Drinking (Heavy)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Drinking (Quit)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Tobacco Chewer', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Tobacco (Quit)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Sedentary lifestyle', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Moderate lifestyle', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Active lifestyle', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Good Diet', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Average Diet', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Poor Diet', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Disturbed Sleep', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Adequate Sleep', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Peaceful Sleep', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Insomnia', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Somnambulism', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Unmarried', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Married', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Divorced', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Widowed', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Consanguineous marriage', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Non-consanguineous marriage', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Children Yes', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Children No', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Regular menses', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Irregular menses', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'Post Menopause', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'HOE-denied', 0, now()),
  (gen_random_uuid(), 'dermatology', 'personal_history', 'NOT BREASTFEEDING', 0, now())
ON CONFLICT (speciality, field, value) DO NOTHING;
