-- Seed dermatology past-medical-history suggestions. Field =
-- 'past_medical_history', specialty = 'dermatology' (matches the lowercase
-- + trimmed normalization done by SuggestionService.resolveSpecialities).
-- Idempotent via ON CONFLICT.
INSERT INTO suggestion (id, speciality, field, value, use_count, created_at) VALUES
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ACNE VULGARIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ACROMEGALY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ACUTE GASTRITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'AID TYPE 1', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'AID TYPE 2', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ALLERGIC BRONCHITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ANAEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'APD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CA THYROID', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CAD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CAH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CENTRAL HYPOTHYROIDISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CHRONIC ANOVULATION WITHOUT HYPERANDROGENISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CKD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CKD - STAGE 1', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CKD - STAGE 2', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CKD - STAGE 3', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CKD - STAGE 4', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CKD - STAGE 5', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'COMBINED HYPERLIPIDEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CONGENITAL HYPOTHYROIDIM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CONSTITUTIONAL DELAYED PUBERT AND GROWTH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'CVD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DENGUE FEVER', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DEPRESSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETES INSIPIDUS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETES MELLITUS TYPE 1', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETES MELLITUS TYPE 2', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETIC FOOT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETIC RETINOPATHY - BACKGROUND', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DIABETIC RETINOPATHY - PROLIFERATIVE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'DYSLIPIDEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'EMPTY SELLA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ESSENTIAL HYPERTENSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'EUTHYROID MNG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'FUNGAL INFECTION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'GDM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'GESTATIONAL DIABETES MELLITUS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'GESTATIONAL THYROTOXICOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'GH DEFICIENCY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'GRAVES DIAGNOSED IN PREGNANCY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'GRAVES ORBITOPATHY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPERGLYCEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPERGLYCERIDEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPERLIPIDEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPERLIPOPROTEINEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPERTENSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPO-HYPO FEMALE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPO-HYPO MALE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPOGLYCEMIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPOTHYROIDISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'HYPOTHYROIDISM DIAGNOSED IN PREGNANCY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'IDIOPATHIC HIRSUTISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'INCIDENTAL ADRENAL TUMOR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'IODINE INDUCED THYROTOXICOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ISCHEMIC HEART DISEASE - MYCOARDIAL INFARCTION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ISCHEMIC HEART DISEASE - STABLE ANGINA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ISCHEMIC HEART DISEASE - UNSTABLE ANGINA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ISOLATED SYSTOLIC HYPERTENSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'ISS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'JUVENILE DIABETES MELLITUS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'LOW UPTAKE IMMUNE THYROTOXICOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'LRTI', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'MALIGNANT HYPERTENSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'MICROALBUMINURIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'MNG WITH TRACHEAL COMPRESSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'NEPHROPATHY SATGE 4', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'NEPHROPATHY STAGE 1', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'NEPHROPATHY STAGE 2', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'NEPHROPATHY STAGE 3', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'NEUROPATHY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'OBESITY – BARIATRIC SURGERY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'OBESITY – METABOLICALLY HEALTHY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'OBESITY – METABOLICALLY UNHEALTHY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PANHYPOPITUITARISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PCOS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PERIPHERAL NEUROPATHY - PAINFUL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PERIPHERAL NEUROPATHY - PAINLESS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PHOBIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'POST PARTUM THYROIDITIS WITH HYPOTHYROIDISM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'POST PARTUM THYROIDITIS WITH THYROTOXICOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PRE DIABETES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PRECOCIOUS PUBERTY CENTRAL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PRECOCIOUS PUBERTY PERIPHERAL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PREMATURE MENOPAUSE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PRIMARY OVARIAN FAILURE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PRIMARY TESTICULAR FAILURE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PSYCHOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'PVD', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'RESISTANT HYPETENSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'RETINOPATHY BG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'RETINOPATHY PDR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SCHIZOPHRENIA', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SECONDARY DM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SECONDARY HYPERTENSION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SIADH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SIMPLE GOITER', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SINUSITIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SOLITARY THYROID NODULE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SUBCLINICAL HYPOTHYROIDISM WITH NEGATIVE ANTIBODIES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'SUBCLINICAL HYPOTHYROIDISM WITH POSITIVE ANTIBODIES', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'THYROID AGENESIS/ECTOPIC THYROID', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'TOXIC MNG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'URTI', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'UTI', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'VERTIGO', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'VIRAL FEVER', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'WARTS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Coronary Angioplasty', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Stent Placement', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Heart bypass surgery', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Appendectomy', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Hysterectomy', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Cholecystectomy', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'Cataract Surgery', 0, now()),
  (gen_random_uuid(), 'dermatology', 'past_medical_history', 'FAMILY H/O VITILIGO', 0, now())
ON CONFLICT (speciality, field, value) DO NOTHING;
