-- Seed dermatology test/investigation suggestions. Field = 'tests',
-- specialty = 'dermatology' (matches the lowercase + trimmed normalization
-- done by SuggestionService.resolveSpecialities). Idempotent via ON CONFLICT.
INSERT INTO suggestion (id, speciality, field, value, use_count, created_at) VALUES
  (gen_random_uuid(), 'dermatology', 'tests', 'THYROID PROFILE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CBP', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'B12 LEVELS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'VITAMIN D3 LEVELS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HIV', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HBSAG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'RBS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'BT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'LFT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FERRITIN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'RFT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'LIPID PROFILE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CBP THYROID LEVELS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG COLOUR DOPPLER-VENOUS OF BOTH LL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'MANTOUX TEST', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FLP', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FBS PPBS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HBA1C', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CUE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FSH LH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SR TESTOSTERONE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SR PRL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HIV-NR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HBSAG-NEGATIVE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CT BT WNL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HCV', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG KUB & PELVIS TO R/O PCOM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SERUM IGE LEVELS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'ESR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'VITAMIN B12 LEVELS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'DHEAS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'AEC', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'TFT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FASTING LIPID PROFILE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'TOTAL BLOOD COUNT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'VDRL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HOMA-IR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SR IGE LEVELS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HIV1 AND HIV 2. HBSAG. HCV. VDRL (TITRES)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'WNL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PROLACTIN', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FREE TESTOSTERONE AND TOTAL TESTOSTERONE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SR CORTISOL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'QUANTIFERON TB GOLD TEST', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG OF THE LESION OVER RT. SIDE OF THE NECK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SLIT SKIN SMEAR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG OF THE LESION OVER SCALP', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'KOH MOUNT FOR RT TOE NAIL CLIPPINGS TO R/O ONYCHOMYCOSIS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CRP', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'TESTS-NORMAL RBS AND FLP HIGH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CBP-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'LFT-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'RFT-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CUE-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FLP-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'TFT-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SUGAR RANDOM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG OF LEFT CHEEK', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG COLOUR DOPPLER-VENOUS OF LEFT LL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG PELVIS/KUB TO R/O', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'ANA TITRE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'ASO TITRE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG OF THE LESION OVER LEFT RETROAURICULAR REGION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'UPT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', '- WNL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'ECG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'TO R/O HANSENS DISEASE ( FAMILY H/O + 10 YEARS AGO )', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SKIN BIOPSY', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PROTHROMBIN TIME', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PARTIAL THROMBOPLASTIN TIME', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SERUM LDH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PERIPHERAL BLOOD SMEAR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'INJ.AVIL/HYDROCORT IV STAT I/C/O BREATHLESSNESS/LIP SWELLING', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HSV IGG IGM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'DEFICIENT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'FH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'LSH', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PLAN FOR EXCISION', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CHEST XRAY(PA VIEW)', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'ANA PROFILE', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SERUM VITAMIN D3', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'NR', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'PLAN FOR ILS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'MNRF', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG OF THE LESION OVER LEFT LATERAL CANTHUS', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'SHBG', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'HSV 2 IGG IGM', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'USG OF THE LESION OVER RT BREAST TO R/O SINUS TRACT', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'CBP LFT RFT RBS FLP -NORMAL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'NORMAL', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'RBS-N', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'Blood Count', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'Complete Foot Examination', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'Fundus Camera', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'Liver Fitness Test', 0, now()),
  (gen_random_uuid(), 'dermatology', 'tests', 'Retinal Examination', 0, now())
ON CONFLICT (speciality, field, value) DO NOTHING;
