import { CSSProperties } from "react";
import { colors, fonts, spacing, radii } from "../../styles/theme";

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.primary200,
    zIndex: 95,
    padding: "24px 40px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    borderRadius: "32px 0 0 0",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    position: "relative",
    marginBottom: "4px",
  },
  backButton: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    border: `1px solid ${colors.neutral300}`,
    backgroundColor: "transparent",
    padding: 0,
  },
  titleContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flex: 1,
    justifyContent: "center",
  },
  title: {
    fontSize: "24px",
    color: colors.neutral900,
    fontFamily: "Libertinus Serif, serif",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  clickableDoctor: {
    textDecoration: "underline",
    cursor: "pointer",
    color: colors.neutral900,
  },
  grid: {
    display: "flex",
    gap: "16px",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  column: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  leftColumn: {
    width: "200px",
  },
  centerColumn: {
    width: "540px",
  },
  rightColumn: {
    width: "300px",
  },
  card: {
    backgroundColor: "white",
    borderRadius: radii.m,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    border: `1px solid ${colors.neutral100}`,
    boxSizing: "border-box",
    width: "100%",
  },
  patientIdCard: {
    alignItems: "center",
    justifyContent: "center",
    padding: "16px",
    height: "100px",
  },
  scheduleMiniCard: {
    padding: "8px 16px",
    height: "unset",
    minHeight: "48px",
    justifyContent: "center",
  },
  patientIdText: {
    fontSize: "40px",
    fontFamily: "Libertinus Serif, serif",
    color: colors.neutral900,
    margin: 0,
  },
  formCard: {
    gap: "16px",
    padding: "16px 24px",
  },
  billingCard: {
    gap: "16px",
    padding: "16px 24px",
    height: "100%",
  },
  appointmentDetailsCard: {
    gap: "12px",
    justifyContent: "center",
  },
  appointmentRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    width: "100%",
  },
  appointmentLabelGroup: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    width: "140px",
    flexShrink: 0,
  },
  appointmentIcon: {
    color: colors.neutral700,
    width: "24px",
    height: "24px",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  fieldLabel: {
    fontSize: "14px",
    fontWeight: 500,
    color: colors.neutral700,
  },
  iconField: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 0",
    borderBottom: `1px solid ${colors.neutral300}`,
    width: "100%",
  },
  iconFieldIcon: {
    color: colors.neutral700,
    width: "24px",
    height: "24px",
    flexShrink: 0,
  },
  iconFieldInput: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: "16px",
    color: colors.neutral900,
    backgroundColor: "transparent",
    padding: 0,
    fontFamily: fonts.family.primary,
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: radii.m,
    border: `1px solid ${colors.neutral300}`,
    fontSize: "15px",
    outline: "none",
    transition: "border-color 0.2s",
  },
  row: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    width: "100%",
  },
  radioGroup: {
    display: "flex",
    gap: "16px",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "16px",
    cursor: "pointer",
    color: colors.neutral900,
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: radii.m,
    border: `1px solid ${colors.neutral300}`,
    fontSize: "15px",
    backgroundColor: "white",
    cursor: "pointer",
  },
  billingRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "14px",
    color: colors.neutral700,
  },
  billingValue: {
    fontWeight: 600,
    color: colors.neutral900,
  },
  totalRow: {
    marginTop: "8px",
    paddingTop: "16px",
    borderTop: `1px solid ${colors.neutral200}`,
    fontSize: "18px",
    fontWeight: 700,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: colors.neutral900,
  },
  buttonGroup: {
    display: "flex",
    gap: "12px",
    marginTop: "auto",
  }
};

